# Generated by Django 4.2.1 on 2023-05-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cart.category'),
        ),
    ]
