# Generated by Django 4.2.1 on 2023-05-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_category_to_link_subcategory_to_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
